version: '3.8'

services:
  db:
    image: postgres:14
    container_name: db-container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    restart: unless-stopped

  downtime_doc_mcp:
    build:
      context: ./downtime_doc_mcp
    ports:
      - "8888:8888"
    depends_on:
      - db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  cron:
    build:
      context: ./cron
    ports:
      - "8008:8008"
    depends_on:
      - db
      - downtime_doc_mcp
      - redis
    command: celery -A main worker -E -l debug
    
  celery-beat:
    build:
      context: ./cron
    depends_on:
      - redis
      - cron
    command: celery -A main beat -l debug

  postgres_mcp_api:
    build:
      context: ./postgres_mcp
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: app_db
      DB_HOST: db
      DB_PORT: 5432
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:

