version: '3.8'

services:
  app:
    image: your-app-image:latest
    # Or build from Dockerfile
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: app-container
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    volumes:
      - ./app:/app
    depends_on:
      - db
    networks:
      - app-network
    restart: unless-stopped

  db:
    image: postgres:14
    container_name: db-container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:

