[project]
name = "cron"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "anthropic>=0.54.0",
    "celery>=5.5.3",
    "httpx>=0.28.1",
    "mcp[cli]>=1.9.3",
    "python-dotenv>=1.1.0",
    "redis>=5.0.1",
]
